---
- name: This playbook creates file or dir
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Creating a directory
      file:
        path: /home/ansadmin/dir1
        state: directory
