--- 
- name: This playbook install httpd or apache2 
  hosts: webserver
  become: true 
  tasks:
    - name: stop httpd
      service:
        name: httpd
        state: stopped
           
    - name: Remove httpd
      yum: 
        name: httpd
        state: absent
