--- 
- name: This playbook install httpd or apache2 
  hosts: webservers
  become: true 
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"  

    - name: Start httpd
      service: 
        name: httpd
        state: restarted
      when: ansible_os_family == "Redhat" 

    - name: enable httpd
      service: 
        name: httpd
        enabled: yes
      when: ansible_os_family == "Redhat" 

    - name: Install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian" 

    - name: Start apache2
      service:
        name: apache2
        state: started 
      when: ansible_os_family == "Debian" 
