---
# tasks file for setup_apache
- name: Install httpd
  ansible.builtin.yum:
    name: httpd
    state: present
    when: ansible_os_family == "RedHat"
    tags: install_apache
    notify: start apache
    ignore_errors: yes

- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  tags: install_apache2 
  notify: start apache2
  ignore_errors: yes

- name: copy index.html
  ansible.builtin.file:
    src: /opt/ansible/index.html
    dest: /var/www/html
    mode: 0666 # give read and write permission
  tags: copy_index
  ignore_errors: yes


- name: Ensure the default Apache port is {{ port }}
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen {{ port }} 
  when: ansible_os_family == "Redhat"
  notify: restart apache
  ignore_errors: yes
    
- name: Ensure the default Apache port is {{ port }} on Debian
  ansible.builtin.lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    insertafter: '^# /etc/apache2/sites-enabled/000-default.conf '
    line: Listen {{ port }}
  when: ansible_os_family == "Debian"
  notify: restart apache2
  ignore_errors: yes
