--- 
- name: This playbook remove httpd or apache2 
  hosts: webserver
  become: true 
  tasks:
    - name: Stop httpd
      service:
        name: httpd
        state: stopped
      when: ansible_os_family == "RedHat"  

    - name: Uninstall httpd
      yum: 
        name: httpd
        state: removed
      when: ansible_os_family == "Redhat" 

    - name: Stop apache2
      service:
        name: apache2
        state: stopped
      when: ansible_os_family == "Debian" 

    - name: Uninstall apache2
      apt:
        name: apache2
        state: absent 
      when: ansible_os_family == "Debian" 
