--- 
- name: This playbook install apache2 
  hosts: webserver
  become: true 
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start apache2
      service: 
        name: apache2
        state: started
