--- 
- name: This playbook remove apache2 
  hosts: webserver
  become: true 
  tasks:
    - name: stop apache2
      service:
        name: apache2
        state: stopped
           
    - name: Remove apache2
      apt: 
        name: apache2
        state: absent
