--- 
- name: This playbook install httpd or apache2 
  hosts: webserver
  become: true 
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start httpd # if do not work: cd /etc/init.d and apachectl start
      service: 
        name: httpd
        state: started
      when: ansible_os_family == "Redhat" 

    - name: enable httpd
      service: 
        name: httpd
        enabled: yes
      when: ansible_os_family == "Redhat" 

    - name: Install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian" 

    - name: Start apache2
      service:
        name: apache2
        state: started 
      when: ansible_os_family == "Debian"

    - name: Remove the default index.html file on Ubuntu
      file:
        path: /var/www/html/index.html
        state: absent
      when: ansible_os_family == "Debian"
   #- name: copy index.html
   #   file:
   #     src: /opt/ansible/index.html
   #     dest: /var/www/html
   #     mode: 0666 # give read and write permission
