---
- name: This playbook Install apache
  hosts: webserver
  become: true
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service:
        name: httpd
        state: started 
        enabled: yes
